[package]
name = "r10c"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "r10c"
required-features = ["cli"]

[features]
cli = ["dep:bpaf", "const_calculator"]
const_calculator = []
default = ["f32", "f64"]
f16 = []
f32 = []
f64 = []
f128 = []

[dependencies]
bpaf = { version = "0.9", optional = true }
