[package]
description = """
Round numbers on a logarithmic scale, using R10c preferred numbers.
"""
edition = "2024"
license = "MIT OR Apache-2.0"
name = "r10c"
repository = "https://github.com/solidsnack/r10c"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "r10c"
required-features = ["cli"]

[features]
cli = ["dep:bpaf", "const_calculator"]
const_calculator = []
default = ["f32", "f64"]
exhaustive = []
f16 = []
f32 = []
f64 = []
f128 = []
wasm = ["dep:wasm-bindgen"]

[dependencies]
assert2 = "0.4"
bitfield-struct = "0.1"
bpaf = { version = "0.9", optional = true }
delegate = "0.13.5"
regex = "1.12.4"
wasm-bindgen = { version = "0.2", optional = true }

[dev-dependencies]
proptest = "1"
wasm-bindgen-test = "0.3"
