name: CI

on:
  push:
    branches: [main, trunk]
  pull_request:

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: swatinem/rust-cache@v2
    - uses: extractions/setup-just@v2
    - run: just test
      env:
        PROPTEST_DISABLE_FAILURE_PERSISTENCE: "1"

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - uses: swatinem/rust-cache@v2
    - uses: extractions/setup-just@v2
    - run: just lint
